CREATE TYPE "public"."clase_cuenta" AS ENUM('ACTIVO', 'PASIVO', 'PATRIMONIO', 'INGRESO', 'GASTO', 'COSTO_VENTAS');--> statement-breakpoint
CREATE TYPE "public"."estado_compra" AS ENUM('BORRADOR', 'RECIBIDA', 'ANULADA');--> statement-breakpoint
CREATE TYPE "public"."estado_conteo" AS ENUM('EN_PROCESO', 'APLICADO', 'DESCARTADO');--> statement-breakpoint
CREATE TYPE "public"."estado_periodo" AS ENUM('ABIERTO', 'CERRADO');--> statement-breakpoint
CREATE TYPE "public"."naturaleza" AS ENUM('DEBITO', 'CREDITO');--> statement-breakpoint
CREATE TYPE "public"."origen_asiento" AS ENUM('APERTURA', 'COMPRA', 'DEVOLUCION_COMPRA', 'VENTA', 'DEVOLUCION_VENTA', 'PAGO_PROVEEDOR', 'RECAUDO_CLIENTE', 'GASTO', 'ARQUEO_CAJA', 'AJUSTE_INVENTARIO', 'MERMA', 'TRASLADO', 'NOMINA', 'IMPUESTOS', 'CIERRE', 'REVERSION', 'MANUAL');--> statement-breakpoint
CREATE TYPE "public"."regimen_consumo" AS ENUM('NINGUNO', 'LICORES', 'CERVEZA', 'CIGARRILLOS');--> statement-breakpoint
CREATE TYPE "public"."rol_usuario" AS ENUM('ADMINISTRADOR', 'CONTADOR', 'CAJERO', 'BODEGA');--> statement-breakpoint
CREATE TYPE "public"."tipo_documento" AS ENUM('CC', 'CE', 'NIT', 'PASAPORTE', 'TI', 'PEP', 'SIN_IDENTIFICAR');--> statement-breakpoint
CREATE TYPE "public"."tipo_impuesto" AS ENUM('IVA', 'CONSUMO_LICORES', 'CONSUMO_CERVEZA', 'CONSUMO_CIGARRILLOS', 'ICA', 'RETEFUENTE');--> statement-breakpoint
CREATE TYPE "public"."tipo_movimiento" AS ENUM('ENTRADA_COMPRA', 'ENTRADA_DEVOLUCION_CLIENTE', 'ENTRADA_AJUSTE', 'ENTRADA_SALDO_INICIAL', 'SALIDA_VENTA', 'SALIDA_DEVOLUCION_PROVEEDOR', 'SALIDA_AJUSTE', 'SALIDA_MERMA', 'TRASLADO_ENTRADA', 'TRASLADO_SALIDA');--> statement-breakpoint
CREATE TYPE "public"."tipo_tercero" AS ENUM('CLIENTE', 'PROVEEDOR', 'AMBOS', 'EMPLEADO');--> statement-breakpoint
CREATE TYPE "public"."tipo_ubicacion" AS ENUM('VENTA', 'BODEGA', 'AVERIAS');--> statement-breakpoint
CREATE TYPE "public"."unidad_base" AS ENUM('UNIDAD', 'ML', 'GRAMO');--> statement-breakpoint
CREATE TABLE "empresa" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"razon_social" varchar(200) NOT NULL,
	"nit" varchar(20) NOT NULL,
	"digito_verificacion" smallint,
	"departamento" varchar(100) NOT NULL,
	"municipio" varchar(100) NOT NULL,
	"direccion" varchar(200),
	"telefono" varchar(40),
	"correo" varchar(200),
	"responsable_iva" boolean DEFAULT true NOT NULL,
	"responsable_consumo" boolean DEFAULT false NOT NULL,
	"regimen_renta" varchar(20) DEFAULT 'ORDINARIO' NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "fila_unica" CHECK ("empresa"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE "periodo_contable" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"anio" integer NOT NULL,
	"mes" smallint NOT NULL,
	"estado" "estado_periodo" DEFAULT 'ABIERTO' NOT NULL,
	"cerrado_en" timestamp with time zone,
	"cerrado_por" uuid,
	CONSTRAINT "periodo_unico" UNIQUE("anio","mes"),
	CONSTRAINT "mes_valido" CHECK ("periodo_contable"."mes" between 1 and 12),
	CONSTRAINT "anio_valido" CHECK ("periodo_contable"."anio" between 2000 and 2200)
);
--> statement-breakpoint
CREATE TABLE "usuario" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar(120) NOT NULL,
	"correo" varchar(200) NOT NULL,
	"rol" "rol_usuario" NOT NULL,
	"activo" boolean DEFAULT true NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "usuario_correo_unique" UNIQUE("correo")
);
--> statement-breakpoint
CREATE TABLE "tercero" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tipo_documento" "tipo_documento" NOT NULL,
	"numero_documento" varchar(30) NOT NULL,
	"digito_verificacion" smallint,
	"nombre" varchar(200) NOT NULL,
	"tipo" "tipo_tercero" NOT NULL,
	"telefono" varchar(40),
	"direccion" varchar(200),
	"correo" varchar(200),
	"cupo_credito" bigint DEFAULT 0 NOT NULL,
	"dias_plazo" smallint DEFAULT 0 NOT NULL,
	"notas" text,
	"activo" boolean DEFAULT true NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "documento_unico" UNIQUE("tipo_documento","numero_documento"),
	CONSTRAINT "cupo_no_negativo" CHECK ("tercero"."cupo_credito" >= 0),
	CONSTRAINT "plazo_no_negativo" CHECK ("tercero"."dias_plazo" >= 0)
);
--> statement-breakpoint
CREATE TABLE "asiento" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"consecutivo" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "asiento_consecutivo_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fecha" date NOT NULL,
	"descripcion" text NOT NULL,
	"origen" "origen_asiento" NOT NULL,
	"documento_tipo" varchar(30),
	"documento_id" uuid,
	"reversa_asiento_id" uuid,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"creado_por" uuid NOT NULL,
	CONSTRAINT "asiento_consecutivo_unique" UNIQUE("consecutivo"),
	CONSTRAINT "descripcion_no_vacia" CHECK (length(trim("asiento"."descripcion")) > 0)
);
--> statement-breakpoint
CREATE TABLE "asiento_linea" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asiento_id" uuid NOT NULL,
	"orden" integer NOT NULL,
	"cuenta_codigo" varchar(20) NOT NULL,
	"debito" bigint DEFAULT 0 NOT NULL,
	"credito" bigint DEFAULT 0 NOT NULL,
	"tercero_id" uuid,
	"descripcion" text,
	CONSTRAINT "linea_orden_unico" UNIQUE("asiento_id","orden"),
	CONSTRAINT "debito_no_negativo" CHECK ("asiento_linea"."debito" >= 0),
	CONSTRAINT "credito_no_negativo" CHECK ("asiento_linea"."credito" >= 0),
	CONSTRAINT "un_solo_lado" CHECK (("asiento_linea"."debito" = 0) <> ("asiento_linea"."credito" = 0))
);
--> statement-breakpoint
CREATE TABLE "cuenta" (
	"codigo" varchar(20) PRIMARY KEY NOT NULL,
	"nombre" varchar(200) NOT NULL,
	"clase" "clase_cuenta" NOT NULL,
	"naturaleza" "naturaleza" NOT NULL,
	"admite_movimiento" boolean DEFAULT true NOT NULL,
	"activa" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categoria_tributaria" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar(100) NOT NULL,
	"regimen_consumo" "regimen_consumo" DEFAULT 'NINGUNO' NOT NULL,
	"cuenta_inventario" varchar(20) NOT NULL,
	"cuenta_ingreso" varchar(20) NOT NULL,
	"cuenta_costo" varchar(20) NOT NULL,
	"activa" boolean DEFAULT true NOT NULL,
	CONSTRAINT "categoria_tributaria_nombre_unique" UNIQUE("nombre")
);
--> statement-breakpoint
CREATE TABLE "codigo_barras" (
	"codigo" varchar(60) PRIMARY KEY NOT NULL,
	"presentacion_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "precio" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"presentacion_id" uuid NOT NULL,
	"precio_venta" bigint NOT NULL,
	"vigencia_desde" date NOT NULL,
	"vigencia_hasta" date,
	"notas" text,
	CONSTRAINT "precio_no_negativo" CHECK ("precio"."precio_venta" >= 0),
	CONSTRAINT "vigencia_coherente" CHECK ("precio"."vigencia_hasta" is null or "precio"."vigencia_hasta" >= "precio"."vigencia_desde")
);
--> statement-breakpoint
CREATE TABLE "presentacion" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producto_id" uuid NOT NULL,
	"nombre" varchar(60) NOT NULL,
	"unidades_base" bigint NOT NULL,
	"es_compra_por_defecto" boolean DEFAULT false NOT NULL,
	"es_venta_por_defecto" boolean DEFAULT false NOT NULL,
	"activa" boolean DEFAULT true NOT NULL,
	CONSTRAINT "presentacion_unica" UNIQUE("producto_id","nombre"),
	CONSTRAINT "unidades_base_positiva" CHECK ("presentacion"."unidades_base" > 0)
);
--> statement-breakpoint
CREATE TABLE "producto" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sku" varchar(40) NOT NULL,
	"nombre" varchar(200) NOT NULL,
	"marca" varchar(100),
	"categoria_tributaria_id" uuid NOT NULL,
	"unidad_base" "unidad_base" NOT NULL,
	"grado_alcoholimetrico_centesimas" integer,
	"contenido_cc" integer,
	"stock_minimo" bigint DEFAULT 0 NOT NULL,
	"controla_lote" boolean DEFAULT true NOT NULL,
	"activo" boolean DEFAULT true NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "producto_sku_unique" UNIQUE("sku"),
	CONSTRAINT "grado_valido" CHECK ("producto"."grado_alcoholimetrico_centesimas" is null or "producto"."grado_alcoholimetrico_centesimas" between 0 and 10000),
	CONSTRAINT "contenido_positivo" CHECK ("producto"."contenido_cc" is null or "producto"."contenido_cc" > 0),
	CONSTRAINT "stock_minimo_no_negativo" CHECK ("producto"."stock_minimo" >= 0)
);
--> statement-breakpoint
CREATE TABLE "conteo_fisico" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"fecha" date NOT NULL,
	"ubicacion_id" uuid NOT NULL,
	"estado" "estado_conteo" DEFAULT 'EN_PROCESO' NOT NULL,
	"asiento_id" uuid,
	"notas" text,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"creado_por" uuid NOT NULL,
	"aplicado_en" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "conteo_fisico_linea" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conteo_id" uuid NOT NULL,
	"producto_id" uuid NOT NULL,
	"lote_id" uuid,
	"cantidad_teorica" bigint NOT NULL,
	"cantidad_contada" bigint NOT NULL,
	"diferencia" bigint GENERATED ALWAYS AS (cantidad_contada - cantidad_teorica) STORED,
	"motivo" text,
	CONSTRAINT "conteo_producto_lote_unico" UNIQUE("conteo_id","producto_id","lote_id"),
	CONSTRAINT "contada_no_negativa" CHECK ("conteo_fisico_linea"."cantidad_contada" >= 0)
);
--> statement-breakpoint
CREATE TABLE "lote" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producto_id" uuid NOT NULL,
	"codigo" varchar(60) NOT NULL,
	"proveedor_id" uuid,
	"factura_proveedor" varchar(60),
	"fecha_vencimiento" date,
	"senalizacion" varchar(80),
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lote_unico_por_producto" UNIQUE("producto_id","codigo")
);
--> statement-breakpoint
CREATE TABLE "movimiento_inventario" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asiento_id" uuid NOT NULL,
	"producto_id" uuid NOT NULL,
	"lote_id" uuid,
	"ubicacion_id" uuid NOT NULL,
	"tipo" "tipo_movimiento" NOT NULL,
	"fecha" date NOT NULL,
	"cantidad" bigint NOT NULL,
	"costo_total" bigint NOT NULL,
	"documento_tipo" varchar(30),
	"documento_id" uuid,
	"notas" text,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"creado_por" uuid NOT NULL,
	CONSTRAINT "cantidad_no_cero" CHECK ("movimiento_inventario"."cantidad" <> 0),
	CONSTRAINT "signo_coherente" CHECK (("movimiento_inventario"."cantidad" > 0 and "movimiento_inventario"."costo_total" >= 0) or ("movimiento_inventario"."cantidad" < 0 and "movimiento_inventario"."costo_total" <= 0))
);
--> statement-breakpoint
CREATE TABLE "saldo_inventario" (
	"producto_id" uuid NOT NULL,
	"ubicacion_id" uuid NOT NULL,
	"cantidad" bigint DEFAULT 0 NOT NULL,
	"costo_total" bigint DEFAULT 0 NOT NULL,
	"actualizado_en" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "saldo_inventario_producto_id_ubicacion_id_pk" PRIMARY KEY("producto_id","ubicacion_id"),
	CONSTRAINT "saldo_cantidad_no_negativa" CHECK ("saldo_inventario"."cantidad" >= 0),
	CONSTRAINT "saldo_costo_no_negativo" CHECK ("saldo_inventario"."costo_total" >= 0),
	CONSTRAINT "cero_es_cero" CHECK (("saldo_inventario"."cantidad" = 0) = ("saldo_inventario"."costo_total" = 0))
);
--> statement-breakpoint
CREATE TABLE "saldo_lote" (
	"lote_id" uuid NOT NULL,
	"ubicacion_id" uuid NOT NULL,
	"cantidad" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "saldo_lote_lote_id_ubicacion_id_pk" PRIMARY KEY("lote_id","ubicacion_id"),
	CONSTRAINT "saldo_lote_no_negativo" CHECK ("saldo_lote"."cantidad" >= 0)
);
--> statement-breakpoint
CREATE TABLE "ubicacion" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar(100) NOT NULL,
	"tipo" "tipo_ubicacion" NOT NULL,
	"activa" boolean DEFAULT true NOT NULL,
	CONSTRAINT "ubicacion_nombre_unique" UNIQUE("nombre")
);
--> statement-breakpoint
CREATE TABLE "compra" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"proveedor_id" uuid NOT NULL,
	"numero_factura" varchar(60) NOT NULL,
	"fecha" date NOT NULL,
	"fecha_vencimiento" date,
	"ubicacion_id" uuid NOT NULL,
	"estado" "estado_compra" DEFAULT 'BORRADOR' NOT NULL,
	"subtotal" bigint DEFAULT 0 NOT NULL,
	"descuento" bigint DEFAULT 0 NOT NULL,
	"flete" bigint DEFAULT 0 NOT NULL,
	"iva_descontable" bigint DEFAULT 0 NOT NULL,
	"retencion_fuente" bigint DEFAULT 0 NOT NULL,
	"total" bigint DEFAULT 0 NOT NULL,
	"asiento_id" uuid,
	"notas" text,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"creado_por" uuid NOT NULL,
	"recibida_en" timestamp with time zone,
	CONSTRAINT "factura_unica_por_proveedor" UNIQUE("proveedor_id","numero_factura"),
	CONSTRAINT "subtotal_no_negativo" CHECK ("compra"."subtotal" >= 0),
	CONSTRAINT "descuento_no_negativo" CHECK ("compra"."descuento" >= 0),
	CONSTRAINT "flete_no_negativo" CHECK ("compra"."flete" >= 0),
	CONSTRAINT "iva_no_negativo" CHECK ("compra"."iva_descontable" >= 0),
	CONSTRAINT "total_no_negativo" CHECK ("compra"."total" >= 0),
	CONSTRAINT "vencimiento_posterior" CHECK ("compra"."fecha_vencimiento" is null or "compra"."fecha_vencimiento" >= "compra"."fecha")
);
--> statement-breakpoint
CREATE TABLE "compra_linea" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"compra_id" uuid NOT NULL,
	"orden" integer NOT NULL,
	"producto_id" uuid NOT NULL,
	"presentacion_id" uuid NOT NULL,
	"lote_id" uuid,
	"cantidad_presentaciones" bigint NOT NULL,
	"unidades_base_snapshot" bigint NOT NULL,
	"cantidad_base" bigint NOT NULL,
	"costo_bruto" bigint NOT NULL,
	"descuento" bigint DEFAULT 0 NOT NULL,
	"flete_prorrateado" bigint DEFAULT 0 NOT NULL,
	"iva_descontable" bigint DEFAULT 0 NOT NULL,
	"impuestos_no_descontables" bigint DEFAULT 0 NOT NULL,
	"costo_inventario" bigint NOT NULL,
	CONSTRAINT "compra_linea_orden_unico" UNIQUE("compra_id","orden"),
	CONSTRAINT "cantidad_presentaciones_positiva" CHECK ("compra_linea"."cantidad_presentaciones" > 0),
	CONSTRAINT "cantidad_base_positiva" CHECK ("compra_linea"."cantidad_base" > 0),
	CONSTRAINT "costo_bruto_no_negativo" CHECK ("compra_linea"."costo_bruto" >= 0),
	CONSTRAINT "costo_inventario_no_negativo" CHECK ("compra_linea"."costo_inventario" >= 0),
	CONSTRAINT "conversion_exacta" CHECK ("compra_linea"."cantidad_base" = ("compra_linea"."cantidad_presentaciones" * "compra_linea"."unidades_base_snapshot") / 1000),
	CONSTRAINT "costo_inventario_coherente" CHECK ("compra_linea"."costo_inventario" = "compra_linea"."costo_bruto" - "compra_linea"."descuento" + "compra_linea"."flete_prorrateado" + "compra_linea"."impuestos_no_descontables")
);
--> statement-breakpoint
CREATE TABLE "parametro_tributario" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar(60) NOT NULL,
	"valor" bigint NOT NULL,
	"vigencia_desde" date NOT NULL,
	"vigencia_hasta" date,
	"fuente" varchar(200) NOT NULL,
	CONSTRAINT "parametro_vigencia_coherente" CHECK ("parametro_tributario"."vigencia_hasta" is null or "parametro_tributario"."vigencia_hasta" >= "parametro_tributario"."vigencia_desde")
);
--> statement-breakpoint
CREATE TABLE "tarifa_impuesto" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tipo" "tipo_impuesto" NOT NULL,
	"categoria_tributaria_id" uuid,
	"numerador" integer,
	"denominador" integer,
	"valor_especifico" bigint,
	"vigencia_desde" date NOT NULL,
	"vigencia_hasta" date,
	"fuente" varchar(200) NOT NULL,
	"notas" text,
	CONSTRAINT "denominador_positivo" CHECK ("tarifa_impuesto"."denominador" is null or "tarifa_impuesto"."denominador" > 0),
	CONSTRAINT "numerador_no_negativo" CHECK ("tarifa_impuesto"."numerador" is null or "tarifa_impuesto"."numerador" >= 0),
	CONSTRAINT "fraccion_completa" CHECK (("tarifa_impuesto"."numerador" is null) = ("tarifa_impuesto"."denominador" is null)),
	CONSTRAINT "algun_componente" CHECK ("tarifa_impuesto"."numerador" is not null or "tarifa_impuesto"."valor_especifico" is not null),
	CONSTRAINT "vigencia_coherente" CHECK ("tarifa_impuesto"."vigencia_hasta" is null or "tarifa_impuesto"."vigencia_hasta" >= "tarifa_impuesto"."vigencia_desde")
);
--> statement-breakpoint
ALTER TABLE "periodo_contable" ADD CONSTRAINT "periodo_contable_cerrado_por_usuario_id_fk" FOREIGN KEY ("cerrado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asiento" ADD CONSTRAINT "asiento_reversa_asiento_id_asiento_id_fk" FOREIGN KEY ("reversa_asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asiento" ADD CONSTRAINT "asiento_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asiento_linea" ADD CONSTRAINT "asiento_linea_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asiento_linea" ADD CONSTRAINT "asiento_linea_cuenta_codigo_cuenta_codigo_fk" FOREIGN KEY ("cuenta_codigo") REFERENCES "public"."cuenta"("codigo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asiento_linea" ADD CONSTRAINT "asiento_linea_tercero_id_tercero_id_fk" FOREIGN KEY ("tercero_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categoria_tributaria" ADD CONSTRAINT "categoria_tributaria_cuenta_inventario_cuenta_codigo_fk" FOREIGN KEY ("cuenta_inventario") REFERENCES "public"."cuenta"("codigo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categoria_tributaria" ADD CONSTRAINT "categoria_tributaria_cuenta_ingreso_cuenta_codigo_fk" FOREIGN KEY ("cuenta_ingreso") REFERENCES "public"."cuenta"("codigo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categoria_tributaria" ADD CONSTRAINT "categoria_tributaria_cuenta_costo_cuenta_codigo_fk" FOREIGN KEY ("cuenta_costo") REFERENCES "public"."cuenta"("codigo") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "codigo_barras" ADD CONSTRAINT "codigo_barras_presentacion_id_presentacion_id_fk" FOREIGN KEY ("presentacion_id") REFERENCES "public"."presentacion"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "precio" ADD CONSTRAINT "precio_presentacion_id_presentacion_id_fk" FOREIGN KEY ("presentacion_id") REFERENCES "public"."presentacion"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "presentacion" ADD CONSTRAINT "presentacion_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "producto" ADD CONSTRAINT "producto_categoria_tributaria_id_categoria_tributaria_id_fk" FOREIGN KEY ("categoria_tributaria_id") REFERENCES "public"."categoria_tributaria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico" ADD CONSTRAINT "conteo_fisico_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico" ADD CONSTRAINT "conteo_fisico_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico" ADD CONSTRAINT "conteo_fisico_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico_linea" ADD CONSTRAINT "conteo_fisico_linea_conteo_id_conteo_fisico_id_fk" FOREIGN KEY ("conteo_id") REFERENCES "public"."conteo_fisico"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico_linea" ADD CONSTRAINT "conteo_fisico_linea_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conteo_fisico_linea" ADD CONSTRAINT "conteo_fisico_linea_lote_id_lote_id_fk" FOREIGN KEY ("lote_id") REFERENCES "public"."lote"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lote" ADD CONSTRAINT "lote_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lote" ADD CONSTRAINT "lote_proveedor_id_tercero_id_fk" FOREIGN KEY ("proveedor_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movimiento_inventario" ADD CONSTRAINT "movimiento_inventario_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movimiento_inventario" ADD CONSTRAINT "movimiento_inventario_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movimiento_inventario" ADD CONSTRAINT "movimiento_inventario_lote_id_lote_id_fk" FOREIGN KEY ("lote_id") REFERENCES "public"."lote"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movimiento_inventario" ADD CONSTRAINT "movimiento_inventario_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movimiento_inventario" ADD CONSTRAINT "movimiento_inventario_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "saldo_inventario" ADD CONSTRAINT "saldo_inventario_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "saldo_inventario" ADD CONSTRAINT "saldo_inventario_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "saldo_lote" ADD CONSTRAINT "saldo_lote_lote_id_lote_id_fk" FOREIGN KEY ("lote_id") REFERENCES "public"."lote"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "saldo_lote" ADD CONSTRAINT "saldo_lote_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra" ADD CONSTRAINT "compra_proveedor_id_tercero_id_fk" FOREIGN KEY ("proveedor_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra" ADD CONSTRAINT "compra_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra" ADD CONSTRAINT "compra_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra" ADD CONSTRAINT "compra_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra_linea" ADD CONSTRAINT "compra_linea_compra_id_compra_id_fk" FOREIGN KEY ("compra_id") REFERENCES "public"."compra"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra_linea" ADD CONSTRAINT "compra_linea_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra_linea" ADD CONSTRAINT "compra_linea_presentacion_id_presentacion_id_fk" FOREIGN KEY ("presentacion_id") REFERENCES "public"."presentacion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compra_linea" ADD CONSTRAINT "compra_linea_lote_id_lote_id_fk" FOREIGN KEY ("lote_id") REFERENCES "public"."lote"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tarifa_impuesto" ADD CONSTRAINT "tarifa_impuesto_categoria_tributaria_id_categoria_tributaria_id_fk" FOREIGN KEY ("categoria_tributaria_id") REFERENCES "public"."categoria_tributaria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tercero_nombre_idx" ON "tercero" USING btree ("nombre");--> statement-breakpoint
CREATE INDEX "asiento_fecha_idx" ON "asiento" USING btree ("fecha");--> statement-breakpoint
CREATE INDEX "asiento_origen_idx" ON "asiento" USING btree ("origen");--> statement-breakpoint
CREATE INDEX "asiento_documento_idx" ON "asiento" USING btree ("documento_tipo","documento_id");--> statement-breakpoint
CREATE INDEX "linea_asiento_idx" ON "asiento_linea" USING btree ("asiento_id");--> statement-breakpoint
CREATE INDEX "linea_cuenta_idx" ON "asiento_linea" USING btree ("cuenta_codigo");--> statement-breakpoint
CREATE INDEX "linea_tercero_idx" ON "asiento_linea" USING btree ("tercero_id");--> statement-breakpoint
CREATE INDEX "codigo_barras_presentacion_idx" ON "codigo_barras" USING btree ("presentacion_id");--> statement-breakpoint
CREATE INDEX "precio_presentacion_idx" ON "precio" USING btree ("presentacion_id","vigencia_desde");--> statement-breakpoint
CREATE INDEX "presentacion_producto_idx" ON "presentacion" USING btree ("producto_id");--> statement-breakpoint
CREATE INDEX "producto_nombre_idx" ON "producto" USING btree ("nombre");--> statement-breakpoint
CREATE INDEX "producto_categoria_idx" ON "producto" USING btree ("categoria_tributaria_id");--> statement-breakpoint
CREATE INDEX "conteo_linea_conteo_idx" ON "conteo_fisico_linea" USING btree ("conteo_id");--> statement-breakpoint
CREATE INDEX "lote_producto_idx" ON "lote" USING btree ("producto_id");--> statement-breakpoint
CREATE INDEX "lote_vencimiento_idx" ON "lote" USING btree ("fecha_vencimiento");--> statement-breakpoint
CREATE INDEX "movimiento_producto_fecha_idx" ON "movimiento_inventario" USING btree ("producto_id","fecha");--> statement-breakpoint
CREATE INDEX "movimiento_lote_idx" ON "movimiento_inventario" USING btree ("lote_id");--> statement-breakpoint
CREATE INDEX "movimiento_asiento_idx" ON "movimiento_inventario" USING btree ("asiento_id");--> statement-breakpoint
CREATE INDEX "movimiento_documento_idx" ON "movimiento_inventario" USING btree ("documento_tipo","documento_id");--> statement-breakpoint
CREATE INDEX "compra_fecha_idx" ON "compra" USING btree ("fecha");--> statement-breakpoint
CREATE INDEX "compra_proveedor_idx" ON "compra" USING btree ("proveedor_id");--> statement-breakpoint
CREATE INDEX "compra_estado_idx" ON "compra" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "compra_linea_compra_idx" ON "compra_linea" USING btree ("compra_id");--> statement-breakpoint
CREATE INDEX "compra_linea_producto_idx" ON "compra_linea" USING btree ("producto_id");--> statement-breakpoint
CREATE INDEX "parametro_vigencia_idx" ON "parametro_tributario" USING btree ("nombre","vigencia_desde");--> statement-breakpoint
CREATE INDEX "tarifa_vigencia_idx" ON "tarifa_impuesto" USING btree ("tipo","vigencia_desde");