CREATE TYPE "public"."estado_turno" AS ENUM('ABIERTO', 'CERRADO');--> statement-breakpoint
CREATE TYPE "public"."estado_venta" AS ENUM('REGISTRADA', 'ANULADA');--> statement-breakpoint
CREATE TYPE "public"."medio_pago" AS ENUM('EFECTIVO', 'DATAFONO', 'TRANSFERENCIA', 'CREDITO');--> statement-breakpoint
CREATE TYPE "public"."tipo_documento_venta" AS ENUM('TIQUETE_POS', 'FACTURA_ELECTRONICA');--> statement-breakpoint
CREATE TABLE "abono_cartera" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cliente_id" uuid NOT NULL,
	"fecha" date NOT NULL,
	"monto" bigint NOT NULL,
	"medio" "medio_pago" NOT NULL,
	"asiento_id" uuid,
	"creado_por" uuid NOT NULL,
	CONSTRAINT "abono_positivo" CHECK ("abono_cartera"."monto" > 0),
	CONSTRAINT "abono_no_a_credito" CHECK ("abono_cartera"."medio" <> 'CREDITO')
);
--> statement-breakpoint
CREATE TABLE "gasto" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"fecha" date NOT NULL,
	"concepto" varchar(200) NOT NULL,
	"cuenta_gasto" varchar(20) NOT NULL,
	"tercero_id" uuid,
	"monto" bigint NOT NULL,
	"medio" "medio_pago" NOT NULL,
	"recurrente_mensual" bigint,
	"asiento_id" uuid,
	"creado_por" uuid NOT NULL,
	CONSTRAINT "gasto_positivo" CHECK ("gasto"."monto" > 0)
);
--> statement-breakpoint
CREATE TABLE "pago_venta" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"venta_id" uuid NOT NULL,
	"medio" "medio_pago" NOT NULL,
	"monto" bigint NOT NULL,
	CONSTRAINT "monto_positivo" CHECK ("pago_venta"."monto" > 0)
);
--> statement-breakpoint
CREATE TABLE "turno_caja" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ubicacion_id" uuid NOT NULL,
	"usuario_id" uuid NOT NULL,
	"abierto_en" timestamp with time zone DEFAULT now() NOT NULL,
	"base_inicial" bigint NOT NULL,
	"estado" "estado_turno" DEFAULT 'ABIERTO' NOT NULL,
	"cerrado_en" timestamp with time zone,
	"efectivo_contado" bigint,
	"diferencia" bigint,
	"asiento_id" uuid,
	"notas" text,
	CONSTRAINT "base_no_negativa" CHECK ("turno_caja"."base_inicial" >= 0)
);
--> statement-breakpoint
CREATE TABLE "venta" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"consecutivo" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "venta_consecutivo_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fecha" date NOT NULL,
	"turno_id" uuid NOT NULL,
	"cliente_id" uuid,
	"tipo_documento" "tipo_documento_venta" DEFAULT 'TIQUETE_POS' NOT NULL,
	"estado" "estado_venta" DEFAULT 'REGISTRADA' NOT NULL,
	"base_gravable" bigint NOT NULL,
	"impuestos" bigint NOT NULL,
	"total" bigint NOT NULL,
	"costo_total" bigint NOT NULL,
	"asiento_id" uuid,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"creado_por" uuid NOT NULL,
	CONSTRAINT "venta_consecutivo_unique" UNIQUE("consecutivo"),
	CONSTRAINT "total_venta_coherente" CHECK ("venta"."total" = "venta"."base_gravable" + "venta"."impuestos"),
	CONSTRAINT "costo_no_negativo" CHECK ("venta"."costo_total" >= 0)
);
--> statement-breakpoint
CREATE TABLE "venta_linea" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"venta_id" uuid NOT NULL,
	"orden" integer NOT NULL,
	"producto_id" uuid NOT NULL,
	"presentacion_id" uuid NOT NULL,
	"lote_id" uuid,
	"cantidad_presentaciones" bigint NOT NULL,
	"unidades_base_snapshot" bigint NOT NULL,
	"cantidad_base" bigint NOT NULL,
	"precio_unitario" bigint NOT NULL,
	"descuento" bigint DEFAULT 0 NOT NULL,
	"base_gravable" bigint NOT NULL,
	"impuestos" bigint NOT NULL,
	"total" bigint NOT NULL,
	"costo_de_salida" bigint NOT NULL,
	CONSTRAINT "venta_linea_orden_unico" UNIQUE("venta_id","orden"),
	CONSTRAINT "cantidad_venta_positiva" CHECK ("venta_linea"."cantidad_base" > 0),
	CONSTRAINT "total_linea_coherente" CHECK ("venta_linea"."total" = "venta_linea"."base_gravable" + "venta_linea"."impuestos")
);
--> statement-breakpoint
ALTER TABLE "abono_cartera" ADD CONSTRAINT "abono_cartera_cliente_id_tercero_id_fk" FOREIGN KEY ("cliente_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "abono_cartera" ADD CONSTRAINT "abono_cartera_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "abono_cartera" ADD CONSTRAINT "abono_cartera_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gasto" ADD CONSTRAINT "gasto_tercero_id_tercero_id_fk" FOREIGN KEY ("tercero_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gasto" ADD CONSTRAINT "gasto_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gasto" ADD CONSTRAINT "gasto_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pago_venta" ADD CONSTRAINT "pago_venta_venta_id_venta_id_fk" FOREIGN KEY ("venta_id") REFERENCES "public"."venta"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turno_caja" ADD CONSTRAINT "turno_caja_ubicacion_id_ubicacion_id_fk" FOREIGN KEY ("ubicacion_id") REFERENCES "public"."ubicacion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turno_caja" ADD CONSTRAINT "turno_caja_usuario_id_usuario_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turno_caja" ADD CONSTRAINT "turno_caja_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta" ADD CONSTRAINT "venta_turno_id_turno_caja_id_fk" FOREIGN KEY ("turno_id") REFERENCES "public"."turno_caja"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta" ADD CONSTRAINT "venta_cliente_id_tercero_id_fk" FOREIGN KEY ("cliente_id") REFERENCES "public"."tercero"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta" ADD CONSTRAINT "venta_asiento_id_asiento_id_fk" FOREIGN KEY ("asiento_id") REFERENCES "public"."asiento"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta" ADD CONSTRAINT "venta_creado_por_usuario_id_fk" FOREIGN KEY ("creado_por") REFERENCES "public"."usuario"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta_linea" ADD CONSTRAINT "venta_linea_venta_id_venta_id_fk" FOREIGN KEY ("venta_id") REFERENCES "public"."venta"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta_linea" ADD CONSTRAINT "venta_linea_producto_id_producto_id_fk" FOREIGN KEY ("producto_id") REFERENCES "public"."producto"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta_linea" ADD CONSTRAINT "venta_linea_presentacion_id_presentacion_id_fk" FOREIGN KEY ("presentacion_id") REFERENCES "public"."presentacion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venta_linea" ADD CONSTRAINT "venta_linea_lote_id_lote_id_fk" FOREIGN KEY ("lote_id") REFERENCES "public"."lote"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "abono_cliente_idx" ON "abono_cartera" USING btree ("cliente_id","fecha");--> statement-breakpoint
CREATE INDEX "gasto_fecha_idx" ON "gasto" USING btree ("fecha");--> statement-breakpoint
CREATE INDEX "pago_venta_idx" ON "pago_venta" USING btree ("venta_id");--> statement-breakpoint
CREATE INDEX "turno_estado_idx" ON "turno_caja" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "venta_fecha_idx" ON "venta" USING btree ("fecha");--> statement-breakpoint
CREATE INDEX "venta_turno_idx" ON "venta" USING btree ("turno_id");--> statement-breakpoint
CREATE INDEX "venta_cliente_idx" ON "venta" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "venta_linea_venta_idx" ON "venta_linea" USING btree ("venta_id");--> statement-breakpoint
CREATE INDEX "venta_linea_producto_idx" ON "venta_linea" USING btree ("producto_id");