export * from './contexto.js';
export * from './libro.js';
export * from './impuestos.js';
export * from './inventario.js';
export * from './compras.js';
export * from './ventas.js';
export * from './tesoreria.js';
export * from './informes.js';
export * from './datos-ejemplo.js';
